import { 
  Command, 
  Search, 
  ShoppingBag, 
  Code2, 
  Flame, 
  Globe, 
  Layers, 
  Workflow, 
  Server, 
  Zap,
  Globe2,
  Cpu,
  Smartphone,
  Layout,
  Terminal,
  Database,
  Cloud,
  FileCode,
  Box,
  FileText,
  BarChart,
  Users,
  Shield
} from "lucide-react"

export const Icons = {
  logo: Command,
  search: Search,
  shopping: ShoppingBag,
  code: Code2,
  flame: Flame,
  globe: Globe,
  layers: Layers,
  workflow: Workflow,
  server: Server,
  zap: Zap,
  // Platform Specific Icons using Lucide placeholders that look clean
  wordpress: Globe2,
  shopify: ShoppingBag,
  magento: Box, 
  bigcommerce: ShoppingBag,
  laravel: Terminal,
  codeigniter: Flame,
  php: FileCode,
  react: Cpu,
  dotnet: Database,
  html: Layout,
  framer: Layers,
  hubspot: Workflow,
  webflow: Cloud,
  vitals: Zap,
  backend: Server,
  // Marketing Specific Icons
  local: Globe,
  onPage: FileText,
  organic: BarChart,
  aso: Smartphone,
  social: Users,
  paid: Zap,
  content: FileText,
  domain: Shield
}
